

#Data used for training the AI
def traning_data_courses():

  training_data = []
  training_data.append({"class":"naturvetenskap", "word":"matematik"})
  training_data.append({"class":"naturvetenskap", "word":"matematik 5"})
  training_data.append({"class":"naturvetenskap", "word":"fysik"})
  training_data.append({"class":"naturvetenskap", "word":"naturvetenskap"})
  training_data.append({"class":"naturvetenskap", "word":"naturvetenskaplig specialisering"})
  training_data.append({"class":"naturvetenskap", "word":"kemi"})
  training_data.append({"class":"naturvetenskap", "word":"biologi"}) #no need to include Biologi a, b or 1, 2 etc. Since we use AI
  training_data.append({"class":"naturvetenskap", "word":"naturkunskap"})

  training_data.append({"class":"mattefysik", "word":"matematik 5"})
  training_data.append({"class":"mattefysik", "word":"matematik - specialisering"})
  training_data.append({"class":"mattefysik", "word":"matematik breddning"})
  training_data.append({"class":"mattefysik", "word":"fysik specialisering"})
  training_data.append({"class":"mattefysik", "word":"fysik breddning"})
  training_data.append({"class":"mattefysik", "word":"fysik 2"})
  training_data.append({"class":"mattefysik", "word":"fysik 3"})

  training_data.append({"class":"kemibiologi", "word":"laboratorieteknik"})
  training_data.append({"class":"kemibiologi", "word":"bioteknik"})
  training_data.append({"class":"kemibiologi", "word":"biologi 2"})

  training_data.append({"class":"teknik", "word":"programmering"})
  training_data.append({"class":"teknik", "word":"teknik"})
  training_data.append({"class":"teknik", "word":"data"})
  training_data.append({"class":"teknik", "word":"dator nätverksteknik"})
  training_data.append({"class":"teknik", "word":"datorteknik"})
  training_data.append({"class":"teknik", "word":"datavetenskap"})
  training_data.append({"class":"teknik", "word":"informations"})
  training_data.append({"class":"teknik", "word":"produktutveckling"})
  training_data.append({"class":"teknik", "word":"tillverkningsteknik"})
  training_data.append({"class":"teknik", "word":"ritteknik"})
  training_data.append({"class":"teknik", "word":"konstruktion"})
  training_data.append({"class":"teknik", "word":"konstruktionsteknik"})
  training_data.append({"class":"teknik", "word":"ledarskap organisation"})
  training_data.append({"class":"teknik", "word":"mekatronik"})
  training_data.append({"class":"teknik", "word":"produktionskunskap"})
  training_data.append({"class":"teknik", "word":"Produktionsteknik"})
  training_data.append({"class":"teknik", "word":"produktionsutrustning"})
  training_data.append({"class":"teknik", "word":"teknik"})
  training_data.append({"class":"teknik", "word":"teknik specialisering"})
  training_data.append({"class":"teknik", "word":"hållbart samhällsbyggande"})
  training_data.append({"class":"teknik", "word":"datorteknik"})
  training_data.append({"class":"teknik", "word":"digital kommunikationsteknik"})
  training_data.append({"class":"teknik", "word":"ellära"})
  training_data.append({"class":"teknik", "word":"energiteknik"})
  training_data.append({"class":"teknik", "word":"geografiska informationssystem"})
  training_data.append({"class":"teknik", "word":"multimediasystem"})
  training_data.append({"class":"teknik", "word":"byggprocessen"})
  training_data.append({"class":"teknik", "word":"miljöcertifierade hus"})
  training_data.append({"class":"teknik", "word":"automationsteknik"})
  training_data.append({"class":"teknik", "word":"produktionskunskap"})
  training_data.append({"class":"teknik", "word":"cad"})
  training_data.append({"class":"teknik", "word":"cad  specialisering"})
  training_data.append({"class":"teknik", "word":"cam"})
  training_data.append({"class":"teknik", "word":"industriell mätteknik"})
  training_data.append({"class":"teknik", "word":"robotteknik"})
  training_data.append({"class":"teknik", "word":"ljud ljus"})
  training_data.append({"class":"teknik", "word":"brandlarmssystem"})
  training_data.append({"class":"teknik", "word":"passersystem"})
  training_data.append({"class":"teknik", "word":"inbrottslarmsystem"})
  training_data.append({"class":"teknik", "word":"CCTV"})
  training_data.append({"class":"teknik", "word":"larm övervaknings säkerhetssystem"})
  training_data.append({"class":"teknik", "word":"produktionsflöden"})
  training_data.append({"class":"teknik", "word":"underhåll"})
  training_data.append({"class":"teknik", "word":"elektronik mikrodatorteknik"})
  training_data.append({"class":"teknik", "word":"låg högfrekvenskretsar"})
  training_data.append({"class":"teknik", "word":"trådlösa radiosystem"})
  training_data.append({"class":"teknik", "word":"kontorstekniksystem"})


  training_data.append({"class":"elektroteknik", "word":"ellära"})
  training_data.append({"class":"elektroteknik", "word":"elmätteknik"})
  training_data.append({"class":"elektroteknik", "word":"elkraftteknik"})
  training_data.append({"class":"elektroteknik", "word":"elektromekanik"})
  training_data.append({"class":"elektroteknik", "word":"låg högfrekvenskretsar"})
  training_data.append({"class":"elektroteknik", "word":"elektronik mikrodatorteknik"})
  training_data.append({"class":"elektroteknik", "word":"mikrodatortillämpningar"})
  training_data.append({"class":"elektroteknik", "word":"högspänningsnät"})
  training_data.append({"class":"elektroteknik", "word":"lågspänningsnät"})
  training_data.append({"class":"elektroteknik", "word":"belysningsnät"})
  training_data.append({"class":"elektroteknik", "word":"stadsnät"})
  training_data.append({"class":"elektroteknik", "word":"nät transformatorstationer"})
  training_data.append({"class":"elektroteknik", "word":"elektronik mikrodatorteknik"})
  training_data.append({"class":"elektroteknik", "word":"låg högfrekvenskretsar"})
  training_data.append({"class":"elektroteknik", "word":"mikrodatortillämpningar"})
  training_data.append({"class":"elektroteknik", "word":"provning kontrollarbete"})
  training_data.append({"class":"elektroteknik", "word":"trådlösa radiosystem"})
  training_data.append({"class":"elektroteknik", "word":"antenn"})

  training_data.append({"class":"fordon", "word":"robotteknik"})
  training_data.append({"class":"fordon", "word":"cad"})
  training_data.append({"class":"fordon", "word":"cam"})
  training_data.append({"class":"fordon", "word":"skeppsteknik"})
  training_data.append({"class":"fordon", "word":"lasthantering passagerarsäkerhet"})
  training_data.append({"class":"fordon", "word":"industriell lackering"})
  training_data.append({"class":"fordon", "word":"lackeringsteknik"})
  training_data.append({"class":"fordon", "word":"lackering"})
  training_data.append({"class":"fordon", "word":"produktionsflöden"})
  training_data.append({"class":"fordon", "word":"grävmaskiner"})
  training_data.append({"class":"fordon", "word":"hjullastare"})
  training_data.append({"class":"fordon", "word":"teleskoplastare"})
  training_data.append({"class":"fordon", "word":"lastmaskiner truckar"})
  training_data.append({"class":"fordon", "word":"väghyvel"})
  training_data.append({"class":"fordon", "word":"anläggningsförare"})

  training_data.append({"class":"verkstandsteknik", "word":"industriell lackering"})
  training_data.append({"class":"verkstandsteknik", "word":"lackeringsteknik"})
  training_data.append({"class":"verkstandsteknik", "word":"lackering"})
  training_data.append({"class":"verkstandsteknik", "word":"lackeringssystem"})
  training_data.append({"class":"verkstandsteknik", "word":"produktionsflöden"})

  training_data.append({"class":"event", "word":"eventteknik"})
  training_data.append({"class":"event", "word":"besöksnäring"})
  training_data.append({"class":"event", "word":"ljudproduktionsteknik"})
  training_data.append({"class":"event", "word":"ljud bildproduktionsteknik"})
  training_data.append({"class":"event", "word":"ljudanläggningar"})
  training_data.append({"class":"event", "word":"aktiviteter upplevelser"})
  training_data.append({"class":"event", "word":"fritidsmiljöer arenor"})
  training_data.append({"class":"event", "word":"evenemang"})
  training_data.append({"class":"event", "word":"konferens"})
  training_data.append({"class":"event", "word":"konferensbokning"})
  training_data.append({"class":"event", "word":"aktivitetsledarskap"})
  training_data.append({"class":"event", "word":"kommunikation"})

  training_data.append({"class":"barn/fritid", "word":"aktiviteter upplevelser"})
  training_data.append({"class":"barn/fritid", "word":"friskvårdsverksamheter"})
  training_data.append({"class":"barn/fritid", "word":"bad"})
  training_data.append({"class":"barn/fritid", "word":"fritidsanläggningar"})
  training_data.append({"class":"barn/fritid", "word":"fritidsmiljöer"})
  training_data.append({"class":"barn/fritid", "word":"fritids"})
  training_data.append({"class":"barn/fritid", "word":"idrottskunskap"})
  training_data.append({"class":"barn/fritid", "word":"naturguidning"})
  training_data.append({"class":"barn/fritid", "word":"guidning naturbruksmiljöer"})
  training_data.append({"class":"barn/fritid", "word":"aktivitetsledarskap"})
  training_data.append({"class":"barn/fritid", "word":"barns lärande och växande"})
  training_data.append({"class":"barn/fritid", "word":"pedagogiskt ledarskap"})
  training_data.append({"class":"barn/fritid", "word":"pedagogiska teorier praktiker"})
  training_data.append({"class":"barn/fritid", "word":"lärande"})
  training_data.append({"class":"barn/fritid", "word":"barn- och ungdomshälsa"})

  training_data.append({"class":"genus", "word":"pedagogiskt ledarskap"})
  training_data.append({"class":"genus", "word":"sociologi"})

  training_data.append({"class":"turism/service", "word":"besöksnäring"})
  training_data.append({"class":"turism/service", "word":"telefon internetservice"})
  training_data.append({"class":"turism/service", "word":"turistbyråservice"})
  training_data.append({"class":"turism/service", "word":"resmålet"})
  training_data.append({"class":"turism/service", "word":"guide reseledare"})
  training_data.append({"class":"turism/service", "word":"vardagsolyckor"})
  training_data.append({"class":"turism/service", "word":"reseproduktion"})
  training_data.append({"class":"turism/service", "word":"internationella relationer"})
  training_data.append({"class":"turism/service", "word":"Receptions konferensservice"})
  training_data.append({"class":"turism/service", "word":"administration"})
  training_data.append({"class":"turism/service", "word":"hållbar turism"})
  training_data.append({"class":"turism/service", "word":"resmål resvägar"})
  training_data.append({"class":"turism/service", "word":"konferens"})
  training_data.append({"class":"turism/service", "word":"rums konferensbokning"})
  training_data.append({"class":"turism/service", "word":"massage"})
  training_data.append({"class":"turism/service", "word":"naturguidning"})
  training_data.append({"class":"turism/service", "word":"aktivitetsledarskap"})

  training_data.append({"class":"räddningstjänst", "word":"akut omhändertagande"})
  training_data.append({"class":"räddningstjänst", "word":"bevakning säkerhet"})
  training_data.append({"class":"räddningstjänst", "word":"brand räddning"})
  training_data.append({"class":"räddningstjänst", "word":"brand räddning"})
  training_data.append({"class":"räddningstjänst", "word":"brandlarmssystem"})
  training_data.append({"class":"räddningstjänst", "word":"passersystem"})
  training_data.append({"class":"räddningstjänst", "word":"inbrottslarmsystem"})
  training_data.append({"class":"räddningstjänst", "word":"CCTVsystem"})
  training_data.append({"class":"räddningstjänst", "word":"larm övervaknings säkerhetssystem"})

  training_data.append({"class":"medicinsk teknik", "word":"Elektromedicinsk teknik"})
  training_data.append({"class":"medicinsk teknik", "word":"Gas vätsketeknik"})
  training_data.append({"class":"medicinsk teknik", "word":"Radiologiska utrustningar"})
  training_data.append({"class":"medicinsk teknik", "word":"laboratorieteknik"})
  training_data.append({"class":"medicinsk teknik", "word":"bioteknik"})
  training_data.append({"class":"medicinsk teknik", "word":"provning kontrollarbete"})
  training_data.append({"class":"medicinsk teknik", "word":"elmätteknik"})

  training_data.append({"class":"data", "word":"datorteknik"})
  training_data.append({"class":"data", "word":"multimediasystem"})
  training_data.append({"class":"data", "word":"datavetenskap"})
  training_data.append({"class":"data", "word":"dator nätverksteknik"})
  training_data.append({"class":"data", "word":"programmering"})
  training_data.append({"class":"data", "word":"informations"})
  training_data.append({"class":"data", "word":"programmerbara styrsystem"})
  training_data.append({"class":"data", "word":"medianät"})
  training_data.append({"class":"data", "word":"robotteknik"})
  training_data.append({"class":"data", "word":"elektronik mikrodatorteknik"})
  training_data.append({"class":"data", "word":"låg högfrekvenskretsar"})
  training_data.append({"class":"data", "word":"mikrodatortillämpningar"})
  training_data.append({"class":"data", "word":"trådlösa radiosystem"})

  training_data.append({"class":"tillverkning konstruktion", "word":"byggprocessen"})
  training_data.append({"class":"tillverkning konstruktion", "word":"industritekniska processer"})
  training_data.append({"class":"tillverkning konstruktion", "word":"produktionsutrustning"})
  training_data.append({"class":"tillverkning konstruktion", "word":"konstruktionsteknik"})
  training_data.append({"class":"tillverkning konstruktion", "word":"konstruktion"})
  training_data.append({"class":"tillverkning konstruktion", "word":"underhåll"})
  training_data.append({"class":"tillverkning konstruktion", "word":"produktutveckling"})
  training_data.append({"class":"tillverkning konstruktion", "word":"produktionskunskap"})
  training_data.append({"class":"tillverkning konstruktion", "word":"tillverkningsteknik"})
  training_data.append({"class":"tillverkning konstruktion", "word":"cad"})
  training_data.append({"class":"tillverkning konstruktion", "word":"tillverkningsteknik"})
  training_data.append({"class":"tillverkning konstruktion", "word":"mekatronik"})
  training_data.append({"class":"tillverkning konstruktion", "word":"Produktionsteknik"})
  training_data.append({"class":"tillverkning konstruktion", "word":"Produktionsutrustning"})
  training_data.append({"class":"tillverkning konstruktion", "word":"produktion"})
  training_data.append({"class":"tillverkning konstruktion", "word":"cam"})
  training_data.append({"class":"tillverkning konstruktion", "word":"industrin"})
  training_data.append({"class":"tillverkning konstruktion", "word":"industriell lackering"})
  training_data.append({"class":"tillverkning konstruktion", "word":"måleri"})
  training_data.append({"class":"tillverkning konstruktion", "word":"provning kontrollarbete"})

  training_data.append({"class":"processteknik", "word":"processmätteknik"})
  training_data.append({"class":"processteknik", "word":"processreglering"})
  training_data.append({"class":"processteknik", "word":"processdatorsystem"})
  training_data.append({"class":"processteknik", "word":"robotteknik"})
  training_data.append({"class":"processteknik", "word":"underhåll"})
  training_data.append({"class":"processteknik", "word":"provning kontrollarbete"})

  training_data.append({"class":"styr/regleteknik", "word":"programmerbara styrsystem"})
  training_data.append({"class":"styr/regleteknik", "word":"reglerteknik"})
  training_data.append({"class":"styr/regleteknik", "word":"styrteknik"})
  training_data.append({"class":"styr/regleteknik", "word":"distribuerande styrsystem"})
  training_data.append({"class":"styr/regleteknik", "word":"elektronik mikrodatorteknik"})
  training_data.append({"class":"styr/regleteknik", "word":"låg högfrekvenskretsar"})

  training_data.append({"class":"samhällsteknik", "word":"geografiska informationssystem"})
  training_data.append({"class":"samhällsteknik", "word":"vindkraftnät"})

  training_data.append({"class":"IT", "word":"webbutveckling"})
  training_data.append({"class":"IT", "word":"webbserverprogrammering"})
  training_data.append({"class":"IT", "word":"webbtjänster"})
  training_data.append({"class":"IT", "word":"programmering"})
  training_data.append({"class":"IT", "word":"medieproduktion"})
  training_data.append({"class":"IT", "word":"dator nätverksteknik"})
  training_data.append({"class":"IT", "word":"datorteknik"})
  training_data.append({"class":"IT", "word":"datorsamordning support"})
  training_data.append({"class":"IT", "word":"digital kommunikationsteknik"})
  training_data.append({"class":"IT", "word":"digitalt skapande"})
  training_data.append({"class":"IT", "word":"gränssnittsdesign"})
  training_data.append({"class":"IT", "word":"gränssnitt"})
  training_data.append({"class":"IT", "word":"multimediasystem"})
  training_data.append({"class":"IT", "word":"Informations medieteknik"})
  training_data.append({"class":"IT", "word":"Informationsteknik"})
  training_data.append({"class":"IT", "word":"Nätverkssäkerhet"})
  training_data.append({"class":"IT", "word":"Nätverksteknik"})
  training_data.append({"class":"IT", "word":"Nätverksteknologier"})
  training_data.append({"class":"IT", "word":"Nätverksadministration"})
  training_data.append({"class":"IT", "word":"administration av nätverks serverutrustning"})
  training_data.append({"class":"IT", "word":"information"})

  training_data.append({"class":"miljö", "word":"miljö"})
  training_data.append({"class":"miljö", "word":"biologi"})
  training_data.append({"class":"miljö", "word":"geografi"})
  training_data.append({"class":"miljö", "word":"miljö energikunskap"})
  training_data.append({"class":"miljö", "word":"hållbart samhällsbyggande"})
  training_data.append({"class":"miljö", "word":"energiteknik"})
  training_data.append({"class":"miljö", "word":"miljöcertifierade hus"})
  training_data.append({"class":"miljö", "word":"politik hållbar"})
  training_data.append({"class":"miljö", "word":"förnybar energi"})
  training_data.append({"class":"miljö", "word":"vatten processkemi"})
  training_data.append({"class":"miljö", "word":"vindkraftnät"})
  training_data.append({"class":"miljö", "word":"dricksvatten"})
  training_data.append({"class":"miljö", "word":"rening av förorenat vatten"})
  training_data.append({"class":"miljö", "word":"bevarandebiologi"})
  training_data.append({"class":"miljö", "word":"vattenreningens mikrobiologi"})
  training_data.append({"class":"miljö", "word":"vattenmiljöer"})

  training_data.append({"class":"ekologi", "word":"djurens"})
  training_data.append({"class":"ekologi", "word":"marken växternas biologi"})
  training_data.append({"class":"ekologi", "word":"bevarandebiologi"})
  training_data.append({"class":"ekologi", "word":"biologi"})
  training_data.append({"class":"ekologi", "word":"naturbruk"})
  training_data.append({"class":"ekologi", "word":"växtodling"})
  training_data.append({"class":"ekologi", "word":"växtkunskap"})
  training_data.append({"class":"ekologi", "word":"trädgårdsodling"})
  training_data.append({"class":"ekologi", "word":"odling"})
  training_data.append({"class":"ekologi", "word":"växthus"})
  training_data.append({"class":"ekologi", "word":"naturturism"})
  training_data.append({"class":"ekologi", "word":"vattenvård"})
  training_data.append({"class":"ekologi", "word":"biodling"})
  training_data.append({"class":"ekologi", "word":"natur landskapsvård"})
  training_data.append({"class":"ekologi", "word":"vattenmiljöer"})

  training_data.append({"class":"naturbruk", "word":"redskap"})
  training_data.append({"class":"naturbruk", "word":"redskap"})
  training_data.append({"class":"naturbruk", "word":"ridning"})
  training_data.append({"class":"naturbruk", "word":"lantbruksdjur"})
  training_data.append({"class":"naturbruk", "word":"mångbruk av skog"})
  training_data.append({"class":"naturbruk", "word":"skogsteknik"})
  training_data.append({"class":"naturbruk", "word":"avverkningsmaskiner"})
  training_data.append({"class":"naturbruk", "word":"terrängtransporter"})
  training_data.append({"class":"naturbruk", "word":"skogsmaskiner"})
  training_data.append({"class":"naturbruk", "word":"lastmaskiner truckar"})

  training_data.append({"class":"djur", "word":"djurhållning"})
  training_data.append({"class":"djur", "word":"hästsportanläggning"})
  training_data.append({"class":"djur", "word":"sällskapsdjur"})
  training_data.append({"class":"djur", "word":"zoohandel"})
  training_data.append({"class":"djur", "word":"hundkunskap"})
  training_data.append({"class":"djur", "word":"djurvård"})
  training_data.append({"class":"djur", "word":"djurens"})
  training_data.append({"class":"djur", "word":"hästkunskap"})
  training_data.append({"class":"djur", "word":"hästens"})
  training_data.append({"class":"djur", "word":"trav"})
  training_data.append({"class":"djur", "word":"djurfoder"})
  training_data.append({"class":"djur", "word":"jakt viltvård"})

  training_data.append({"class":"byggande/samhällsplanering", "word":"hållbart samhällsbyggande"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"vatten processkemi"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"miljöcertifierade hus"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"politik hållbar"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"yttre miljö"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"anläggning"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"bygg"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"anläggningsprocessen"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"beläggning"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"beläggningsmaskiner"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"beläggningsarbeten"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"bergarbeten"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"bergborrning"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"bergmaskiner"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"bergsprängning"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"betong"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"elementmontering"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"golvläggning"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"husbyggnad"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"husbyggnadsprocessen"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"byggnadsunderhåll"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"järnvägsbyggnad"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"ventilationsplåtslageri"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"plåtslageri"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"plåtslageriprocessen"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"vindkraftnät"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"stadsnät"})
  training_data.append({"class":"byggande/samhällsplanering", "word":"fastighetsautomation"})

  training_data.append({"class":"design", "word":"arkitektur"})
  training_data.append({"class":"design", "word":"byggprocessen"})
  training_data.append({"class":"design", "word":"bild"})
  training_data.append({"class":"design", "word":"ritteknik"})
  training_data.append({"class":"design", "word":"design"})
  training_data.append({"class":"design", "word":"designmodeller"})
  training_data.append({"class":"design", "word":"cad"})
  training_data.append({"class":"design", "word":"3D"})
  training_data.append({"class":"design", "word":"visualisering"})
  training_data.append({"class":"design", "word":"produktutveckling"})
  training_data.append({"class":"design", "word":"tillverkningsteknik"})
  training_data.append({"class":"design", "word":"skissteknik"})
  training_data.append({"class":"design", "word":"formgivning"})
  training_data.append({"class":"design", "word":"photoshop"})
  training_data.append({"class":"design", "word":"illustrator"})
  training_data.append({"class":"design", "word":"konstruktion"})
  training_data.append({"class":"design", "word":"konstruktionsteknik"})
  training_data.append({"class":"design", "word":"digitalt skapande"})
  training_data.append({"class":"design", "word":"utställningsdesign"})
  training_data.append({"class":"design", "word":"form"})
  training_data.append({"class":"design", "word":"ljud ljus"})
  training_data.append({"class":"design", "word":"måleri"})

  training_data.append({"class":"arkitektur", "word":"arkitektur"})
  training_data.append({"class":"arkitektur", "word":"ritteknik"})
  training_data.append({"class":"arkitektur", "word":"3d"})
  training_data.append({"class":"arkitektur", "word":"formgivning"})
  training_data.append({"class":"arkitektur", "word":"photoshop"})
  training_data.append({"class":"arkitektur", "word":"illustrator"})
  training_data.append({"class":"arkitektur", "word":"visualisering"})
  training_data.append({"class":"arkitektur", "word":"skissteknik"})
  training_data.append({"class":"arkitektur", "word":"konstarterna samhället"})
  training_data.append({"class":"arkitektur", "word":"digitalt skapande"})
  training_data.append({"class":"arkitektur", "word":"utställningsdesign"})
  training_data.append({"class":"arkitektur", "word":"visuell"})
  training_data.append({"class":"arkitektur", "word":"bild form specialisering"})
  training_data.append({"class":"arkitektur", "word":"form"})
  training_data.append({"class":"arkitektur", "word":"bild"})
  training_data.append({"class":"arkitektur", "word":"husbyggnad"})
  training_data.append({"class":"arkitektur", "word":"husbyggnadsprocessen"})

  training_data.append({"class":"konst", "word":"konst"})
  training_data.append({"class":"konst", "word":"dansgestaltning"})
  training_data.append({"class":"konst", "word":"gestaltning"})
  training_data.append({"class":"konst", "word":"utställningsdesign"})
  training_data.append({"class":"konst", "word":"visuell"})
  training_data.append({"class":"konst", "word":"litteratur"})
  training_data.append({"class":"konst", "word":"skrivande"})
  training_data.append({"class":"konst", "word":"regi"})
  training_data.append({"class":"konst", "word":"teater"})
  training_data.append({"class":"konst", "word":"måleri"})
  training_data.append({"class":"konst", "word":"repertoar"})

  training_data.append({"class":"media", "word":"film"})
  training_data.append({"class":"media", "word":"filmtvkunskap"})
  training_data.append({"class":"media", "word":"radio"})
  training_data.append({"class":"media", "word":"ljudproduktion"})
  training_data.append({"class":"media", "word":"radioproduktion"})
  training_data.append({"class":"media", "word":"webbutveckling"})
  training_data.append({"class":"media", "word":"programmering"})
  training_data.append({"class":"media", "word":"journalistik"})
  training_data.append({"class":"media", "word":"photoshop"})
  training_data.append({"class":"media", "word":"animation"})
  training_data.append({"class":"media", "word":"animation specialisering"})
  training_data.append({"class":"media", "word":"illustrator"})
  training_data.append({"class":"media", "word":"tv produktion"})
  training_data.append({"class":"media", "word":"film produktion"})
  training_data.append({"class":"media", "word":"digitalt skapande"})
  training_data.append({"class":"media", "word":"medieproduktion"})
  training_data.append({"class":"media", "word":"Medier"})
  training_data.append({"class":"media", "word":"musikproduktion"})
  training_data.append({"class":"media", "word":"textkommunikation"})
  training_data.append({"class":"media", "word":"tv"})
  training_data.append({"class":"media", "word":"manus"})
  training_data.append({"class":"media", "word":"fotografisk bild"})
  training_data.append({"class":"media", "word":"illustration"})
  training_data.append({"class":"media", "word":"grafisk"})
  training_data.append({"class":"media", "word":"skrivande"})
  training_data.append({"class":"media", "word":"ljud ljus"})
  training_data.append({"class":"media", "word":"prepress"})
  training_data.append({"class":"media", "word":"kommunikation"})


  training_data.append({"class":"journalistik", "word":"journalistik"})
  training_data.append({"class":"journalistik", "word":"reklam"})
  training_data.append({"class":"journalistik", "word":"textkommunikation"})
  training_data.append({"class":"journalistik", "word":"filmtvkunskap"})
  training_data.append({"class":"journalistik", "word":"radio"})
  training_data.append({"class":"journalistik", "word":"skrivande"})
  training_data.append({"class":"journalistik", "word":"kommunikation"})

  training_data.append({"class":"kultur", "word":"kultur"})
  training_data.append({"class":"kultur", "word":"idéhistoria"})
  training_data.append({"class":"kultur", "word":"kulturuttryck"})
  training_data.append({"class":"kultur", "word":"människans språk"})
  training_data.append({"class":"kultur", "word":"etnicitet"})
  training_data.append({"class":"kultur", "word":"kulturmöten"})
  training_data.append({"class":"kultur", "word":"litteratur"})
  training_data.append({"class":"kultur", "word":"hälsopedagogik"})

  training_data.append({"class":"dans,teater musik", "word":"dansteknik"})
  training_data.append({"class":"dans,teater musik", "word":"dansträning"})
  training_data.append({"class":"dans,teater musik", "word":"dansgestaltning"})
  training_data.append({"class":"dans,teater musik", "word":"dansimprovisation"})
  training_data.append({"class":"dans,teater musik", "word":"komposition"})
  training_data.append({"class":"dans,teater musik", "word":"dansorientering"})
  training_data.append({"class":"dans,teater musik", "word":"gestaltning"})
  training_data.append({"class":"dans,teater musik", "word":"dansteori"})
  training_data.append({"class":"dans,teater musik", "word":"dramatik"})
  training_data.append({"class":"dans,teater musik", "word":"dramapedagogik"})
  training_data.append({"class":"dans,teater musik", "word":"musik"})
  training_data.append({"class":"dans,teater musik", "word":"ensemble"})
  training_data.append({"class":"dans,teater musik", "word":"musikproduktion"})
  training_data.append({"class":"dans,teater musik", "word":"musikimprovisation"})
  training_data.append({"class":"dans,teater musik", "word":"rytmik"})
  training_data.append({"class":"dans,teater musik", "word":"instrument"})
  training_data.append({"class":"dans,teater musik", "word":"sång"})
  training_data.append({"class":"dans,teater musik", "word":"komposition"})
  training_data.append({"class":"dans,teater musik", "word":"gehörs"})
  training_data.append({"class":"dans,teater musik", "word":"körsång"})
  training_data.append({"class":"dans,teater musik", "word":"kör"})
  training_data.append({"class":"dans,teater musik", "word":"sjunga"})
  training_data.append({"class":"dans,teater musik", "word":"repertoar"})
  training_data.append({"class":"dans,teater musik", "word":"Dramapedagogik"})
  training_data.append({"class":"dans,teater musik", "word":"skapande"})
  training_data.append({"class":"dans,teater musik", "word":"regi"})
  training_data.append({"class":"dans,teater musik", "word":"röst"})
  training_data.append({"class":"dans,teater musik", "word":"koreografi"})
  training_data.append({"class":"dans,teater musik", "word":"ljud ljus"})
  training_data.append({"class":"dans,teater musik", "word":"teater"})
  training_data.append({"class":"dans,teater musik", "word":"teaterteori"})
  training_data.append({"class":"dans,teater musik", "word":"scenografi"})
  training_data.append({"class":"dans,teater musik", "word":"kostym"})
  training_data.append({"class":"dans,teater musik", "word":"sceniskt"})
  training_data.append({"class":"dans,teater musik", "word":"dirigering"})
  training_data.append({"class":"dans,teater musik", "word":"bruksspel"})

  training_data.append({"class":"social", "word":"retorikska"})
  training_data.append({"class":"social", "word":"social"})
  training_data.append({"class":"social", "word":"retorik"})
  training_data.append({"class":"social", "word":"pedagogik"})
  training_data.append({"class":"social", "word":"sociologi"})
  training_data.append({"class":"social", "word":"kommunikation"})
  training_data.append({"class":"social", "word":"pedagogisk"})
  training_data.append({"class":"social", "word":"människors"})
  training_data.append({"class":"social", "word":"barns"})
  training_data.append({"class":"social", "word":"lärande"})
  training_data.append({"class":"social", "word":"ungdomskultur"})
  training_data.append({"class":"social", "word":"etnicitet"})
  training_data.append({"class":"social", "word":"aktivitetsledarskap"})
  training_data.append({"class":"social", "word":"hälsopedagogik"})
  training_data.append({"class":"social", "word":"friskvård"})
  training_data.append({"class":"social", "word":"omsorg"})

  training_data.append({"class":"språk", "word":"språk"})
  training_data.append({"class":"språk", "word":"moderna språk"})
  training_data.append({"class":"språk", "word":"kinesiska"})
  training_data.append({"class":"språk", "word":"franska"})
  training_data.append({"class":"språk", "word":"japanska"})
  training_data.append({"class":"språk", "word":"italienska"})
  training_data.append({"class":"språk", "word":"latin"})
  training_data.append({"class":"språk", "word":"ryska"})
  training_data.append({"class":"språk", "word":"polska"})
  training_data.append({"class":"språk", "word":"persiska"})
  training_data.append({"class":"språk", "word":"syriska"})
  training_data.append({"class":"språk", "word":"turkiska"})
  training_data.append({"class":"språk", "word":"ungerska"})
  training_data.append({"class":"språk", "word":"somaliska"})
  training_data.append({"class":"språk", "word":"kroatiska"})
  training_data.append({"class":"språk", "word":"albanska"})
  training_data.append({"class":"språk", "word":"serbiska"})
  training_data.append({"class":"språk", "word":"vietnamesiska"})
  training_data.append({"class":"språk", "word":"pashto"})
  training_data.append({"class":"språk", "word":"thai"})
  training_data.append({"class":"språk", "word":"finska"})
  training_data.append({"class":"språk", "word":"bulgariska"})
  training_data.append({"class":"språk", "word":"danska"})
  training_data.append({"class":"språk", "word":"norska"})
  training_data.append({"class":"språk", "word":"dari"})
  training_data.append({"class":"språk", "word":"tigrinja"})
  training_data.append({"class":"språk", "word":"madnarin"})
  training_data.append({"class":"språk", "word":"spanska"})
  training_data.append({"class":"språk", "word":"arabiska"})
  training_data.append({"class":"språk", "word":"svenska"})
  training_data.append({"class":"språk", "word":"engelska"})
  training_data.append({"class":"språk", "word":"grekiska"})
  training_data.append({"class":"språk", "word":"latin"})
  training_data.append({"class":"språk", "word":"skrivande"})

  training_data.append({"class":"pedagogik", "word":"pedagogisk"})
  training_data.append({"class":"pedagogik", "word":"kommunikation"})
  training_data.append({"class":"pedagogik", "word":"pedagogik"})
  training_data.append({"class":"pedagogik", "word":"retorik"})
  training_data.append({"class":"pedagogik", "word":"lärande"})
  training_data.append({"class":"pedagogik", "word":"barns lärande växande"})
  training_data.append({"class":"pedagogik", "word":"skrivande"})
  training_data.append({"class":"pedagogik", "word":"aktivitetsledarskap"})
  training_data.append({"class":"pedagogik", "word":"pedagogiska"})
  training_data.append({"class":"pedagogik", "word":"specialpedagogik"})

  training_data.append({"class":"fysisk hälsa", "word":"biologi breddning"})
  training_data.append({"class":"fysisk hälsa", "word":"ergonomi"})
  training_data.append({"class":"fysisk hälsa", "word":"fritids"})
  training_data.append({"class":"fysisk hälsa", "word":"idrott"})
  training_data.append({"class":"fysisk hälsa", "word":"hemsjukvård"})
  training_data.append({"class":"fysisk hälsa", "word":"massage"})
  training_data.append({"class":"fysisk hälsa", "word":"träningslära"})
  training_data.append({"class":"fysisk hälsa", "word":"ungdomshälsa"})

  training_data.append({"class":"träning", "word":"idrottsledarskap"})
  training_data.append({"class":"träning", "word":"idrottsspecialisering"})
  training_data.append({"class":"träning", "word":"tävlingslära"})
  training_data.append({"class":"träning", "word":"idrott"})

  training_data.append({"class":"beteende", "word":"Beteendevetenskap"})
  training_data.append({"class":"beteende", "word":"ergonomi"})
  training_data.append({"class":"beteende", "word":"psykologi"})

  training_data.append({"class":"mat hälsa", "word":"kostvetenskap"})
  training_data.append({"class":"mat hälsa", "word":"kost"})
  training_data.append({"class":"mat hälsa", "word":"hälsopedagogik"})
  training_data.append({"class":"mat hälsa", "word":"hygien"})
  training_data.append({"class":"mat hälsa", "word":"livsmedel"})

  training_data.append({"class":"mat nutrion", "word":"Livsmedel"})
  training_data.append({"class":"mat nutrion", "word":"hälsopedagogik"})
  training_data.append({"class":"mat nutrion", "word":"specialkoster"})
  training_data.append({"class":"mat nutrion", "word":"matlagning"})

  training_data.append({"class":"mental hälsa", "word":"psykologi"})
  training_data.append({"class":"mental hälsa", "word":"psykiatri"})
  training_data.append({"class":"mental hälsa", "word":"rättspsykiatri"})
  training_data.append({"class":"mental hälsa", "word":"mental träning"})
  training_data.append({"class":"mental hälsa", "word":"människan"})
  training_data.append({"class":"mental hälsa", "word":"hälsopedagogik"})

  training_data.append({"class":"omvårdnand", "word":"massage"})
  training_data.append({"class":"omvårdnand", "word":"människors"})
  training_data.append({"class":"omvårdnand", "word":"omsorg"})
  training_data.append({"class":"omvårdnand", "word":"barnhälsovård"})
  training_data.append({"class":"omvårdnand", "word":"akutsjukvård"})
  training_data.append({"class":"omvårdnand", "word":"hemsjukvård"})
  training_data.append({"class":"omvårdnand", "word":"omhändertagande"})
  training_data.append({"class":"omvårdnand", "word":"akut massage"})
  training_data.append({"class":"omvårdnand", "word":"ungdomssjukvård"})
  training_data.append({"class":"omvårdnand", "word":"komplementärmedicin"})
  training_data.append({"class":"omvårdnand", "word":"palliativ"})
  training_data.append({"class":"omvårdnand", "word":"socialt arbete"})
  training_data.append({"class":"omvårdnand", "word":"social omsorg"})
  training_data.append({"class":"omvårdnand", "word":"vård"})
  training_data.append({"class":"omvårdnand", "word":"vårdpedagogik"})
  training_data.append({"class":"omvårdnand", "word":"omsorgsarbete"})
  training_data.append({"class":"omvårdnand", "word":"vård och omsorg – specialisering"})
  training_data.append({"class":"omvårdnand", "word":"sjukvård"})
  training_data.append({"class":"omvårdnand", "word":"omvårdnad"})

  training_data.append({"class":"medicin", "word":"kemi"})
  training_data.append({"class":"medicin", "word":"biologi"})
  training_data.append({"class":"medicin", "word":"biologi breddning"})
  training_data.append({"class":"medicin", "word":"psykiatri"})
  training_data.append({"class":"medicin", "word":"rättspsykiatri"})
  training_data.append({"class":"medicin", "word":"medicin"})
  training_data.append({"class":"medicin", "word":"räddningsmedicin"})
  training_data.append({"class":"medicin", "word":"akutsjukvård"})
  training_data.append({"class":"medicin", "word":"anatomi fysiologi"})
  training_data.append({"class":"medicin", "word":"ungdomssjukvård"})
  training_data.append({"class":"medicin", "word":"komplementärmedicin"})
  training_data.append({"class":"medicin", "word":"munhälsa"})
  training_data.append({"class":"medicin", "word":"sjukvård"})


  training_data.append({"class":"konst", "word":"bild"})
  training_data.append({"class":"konst", "word":"konst"})
  training_data.append({"class":"konst", "word":"form"})
  training_data.append({"class":"konst", "word":"arkitektur"})
  training_data.append({"class":"konst", "word":"idéhistoria"})

  training_data.append({"class":"humanioria", "word":"historia"})
  training_data.append({"class":"humanioria", "word":"filosofi"})
  training_data.append({"class":"humanioria", "word":"konst"})
  training_data.append({"class":"humanioria", "word":"bild"})
  training_data.append({"class":"humanioria", "word":"estet"})
  training_data.append({"class":"humanioria", "word":"estetisk"})
  training_data.append({"class":"humanioria", "word":"genus"})
  training_data.append({"class":"humanioria", "word":"kultur"})
  training_data.append({"class":"humanioria", "word":"religionskunskap"})
  training_data.append({"class":"humanioria", "word":"religion"})
  training_data.append({"class":"humanioria", "word":"religionskunskap specialisering"})
  training_data.append({"class":"humanioria", "word":"humanistisk samhällsvetenskaplig specialisering"})
  training_data.append({"class":"humanioria", "word":"litteratur"})

  training_data.append({"class":"ekonomi", "word":"projektledning"})
  training_data.append({"class":"ekonomi", "word":"pedagogisk ledarskap"})
  training_data.append({"class":"ekonomi", "word":"ekonomi"})
  training_data.append({"class":"ekonomi", "word":"entreprenörskap"})
  training_data.append({"class":"ekonomi", "word":"företagande"})
  training_data.append({"class":"ekonomi", "word":"försäljning"})
  training_data.append({"class":"ekonomi", "word":"försäljning kundservice"})
  training_data.append({"class":"ekonomi", "word":"personlig försäljning"})
  training_data.append({"class":"ekonomi", "word":"företagsekonomi"})
  training_data.append({"class":"ekonomi", "word":"företagsekonomi specialisering"})
  training_data.append({"class":"ekonomi", "word":"redovisning"})
  training_data.append({"class":"ekonomi", "word":"administration"})
  training_data.append({"class":"ekonomi", "word":"branschkunskap inom handel administration"})
  training_data.append({"class":"ekonomi", "word":"personaladministration"})
  training_data.append({"class":"ekonomi", "word":"personal"})
  training_data.append({"class":"ekonomi", "word":"ledarskap organisation"})
  training_data.append({"class":"ekonomi", "word":"inköp"})
  training_data.append({"class":"ekonomi", "word":"logistik"})
  training_data.append({"class":"ekonomi", "word":"näthandel"})
  training_data.append({"class":"ekonomi", "word":"konferensservice"})
  training_data.append({"class":"ekonomi", "word":"reception"})
  training_data.append({"class":"ekonomi", "word":"internationella relationer"})
  training_data.append({"class":"ekonomi", "word":"servicekunskap"})
  training_data.append({"class":"ekonomi", "word":"internetservice"})
  training_data.append({"class":"ekonomi", "word":"handel"})

  training_data.append({"class":"ledarskap", "word":"personal"})
  training_data.append({"class":"ledarskap", "word":"projektledning"})
  training_data.append({"class":"ledarskap", "word":"pedagogisk ledarskap"})
  training_data.append({"class":"ledarskap", "word":"administration"})
  training_data.append({"class":"ledarskap", "word":"ledarskap organisation"})
  training_data.append({"class":"ledarskap", "word":"affärsutveckling ledarskap"})

  training_data.append({"class":"entreprenörskap", "word":"entreprenörskap"})
  training_data.append({"class":"entreprenörskap", "word":"marknadsföring"})
  training_data.append({"class":"entreprenörskap", "word":"marknadsföring"})
  training_data.append({"class":"entreprenörskap", "word":"företagande"})
  training_data.append({"class":"entreprenörskap", "word":"affärsutveckling"})
  training_data.append({"class":"entreprenörskap", "word":"programhantering"})
  training_data.append({"class":"entreprenörskap", "word":"intern extern kommunikation"})

  training_data.append({"class":"HR", "word":"personal"})
  training_data.append({"class":"HR", "word":"personaladministration"})
  training_data.append({"class":"HR", "word":"administration"})

  training_data.append({"class":"juridik", "word":"redovisning"})
  training_data.append({"class":"juridik", "word":"juridik"})
  training_data.append({"class":"juridik", "word":"rättskunskap"})
  training_data.append({"class":"juridik", "word":"affärsjuridik"})
  training_data.append({"class":"juridik", "word":"rätten"})
  training_data.append({"class":"juridik", "word":"rätts"})
  training_data.append({"class":"juridik", "word":"rätten samhället"})
  training_data.append({"class":"juridik", "word":"privatjuridik"})
  training_data.append({"class":"juridik", "word":"människan"})
  training_data.append({"class":"juridik", "word":"hälsopedagogik"})
  training_data.append({"class":"juridik", "word":"rättspsykiatri"})

  training_data.append({"class":"samhällsvetenskap", "word":"ekonomi"})
  training_data.append({"class":"samhällsvetenskap", "word":"politik"})
  training_data.append({"class":"samhällsvetenskap", "word":"sociologi"})
  training_data.append({"class":"samhällsvetenskap", "word":"projekt"})
  training_data.append({"class":"samhällsvetenskap", "word":"Humanistisk samhällsvetenskaplig specialisering"}) #data
  training_data.append({"class":"samhällsvetenskap", "word":"samhällskunskap"})
  training_data.append({"class":"samhällsvetenskap", "word":"litteratur"})
  training_data.append({"class":"samhällsvetenskap", "word":"sociologi"})#traning_data=
  training_data.append({"class":"samhällsvetenskap", "word":"geografi"})#data
  training_data.append({"class":"samhällsvetenskap", "word":"engelska"})#data
  training_data.append({"class":"samhällsvetenskap", "word":"svenska"}) #data

  training_data.append({"class":"övrigt", "word":"övrigt"}) #data

  return training_data


print(len(traning_data_courses()))